_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    NAME: RotatedAnchorGenerator
    ANGLES: [[-90,-60,-30,0,30,60,90]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  PROPOSAL_GENERATOR:
    NAME: RRPN
  RPN:
    BBOX_REG_WEIGHTS: (1,1,1,1,1,)
  ROI_BOX_HEAD:
    POOLER_TYPE: ROIAlignRotated
    BBOX_REG_WEIGHTS: (10,10,5,5,5)
  ROI_HEADS:
    NAME: RROIHeads
SOLVER:
  MAX_ITER: 360000
  STEPS: (250000, 330000)
  IMS_PER_BATCH: 4
  BASE_LR: 0.003
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000 
DATASETS:
  TRAIN: ('coco_2017_train_rbbox',)
  TEST: ('coco_2017_val_rbbox',)
OUTPUT_DIR: './output'
